Added ui to manage tasks
wachterjohannes/sulu pull request #2
Opened 2016-11-21 08:07 UTC by wachterjohannes

Add ui to manage tasks.

Basic PR: https://github.com/sulu/sulu/pull/3037

2016-11-22 14:24 UTC, wachterjohannes commented on src/Sulu/Bundle/AutomationBundle/Resources/public/dist/components/automation-tab/overlay/form.html
> +                 data-aura-data='[{"id":"sulu_content.publish","title":"Publish"},{"id":"sulu_content.unpublish","title":"Unpublish"}]'
only data for testing. will be fetched in one of the next PR.

2016-11-22 14:29 UTC, wachterjohannes commented
@danrot

2016-11-23 13:01 UTC, danrot requested changes
Tried to test it, but I couldn't see any tab after registering the SuluAutomationBundle.

2016-11-23 13:01 UTC, danrot commented on src/Sulu/Bundle/AutomationBundle/Resources/public/js/main.js
> +        'services/suluautomation/task-manager': '../../suluautomation/js/services/task-manager'
Is that really necessary? I thought that's only required when we have the a validation type, where the path doesn't match.

2016-11-23 13:01 UTC, danrot commented on src/Sulu/Bundle/AutomationBundle/Resources/public/js/services/task-manager.js
> +    return new Manager();
Any reason this "complicated" structure is required? Why not simply returning an object?

2016-11-23 15:16 UTC, wachterjohannes commented on src/Sulu/Bundle/AutomationBundle/Resources/public/js/main.js
> +        'services/suluautomation/task-manager': '../../suluautomation/js/services/task-manager'
i thought we decided to "normalize" the service ids in this structure

2016-11-23 15:16 UTC, wachterjohannes commented on src/Sulu/Bundle/AutomationBundle/Resources/public/js/services/task-manager.js
> +    return new Manager();
not really its mainly copied (:

2016-11-23 15:18 UTC, danrot commented on src/Sulu/Bundle/AutomationBundle/Resources/public/js/main.js
> +        'services/suluautomation/task-manager': '../../suluautomation/js/services/task-manager'
Haven't heard about that yet... Have we already done that somewhere?

2016-11-23 15:20 UTC, wachterjohannes commented on src/Sulu/Bundle/AutomationBundle/Resources/public/js/main.js
> +        'services/suluautomation/task-manager': '../../suluautomation/js/services/task-manager'
yes category, media, contact ... bundle

2016-11-23 15:29 UTC, wachterjohannes commented
@danrot i have excluded the tab on the startpage but after discussion it doenst make sense. so you can review it now also on the startpage.

2016-11-24 16:55 UTC, danrot commented
After selecting a valid date, the form still shows it as invalid:
![image](https://cloud.githubusercontent.com/assets/405874/20606108/2ae4e1d2-b26f-11e6-8956-5e4f01764f20.png)

Can still be added by a click on the ok button though.

2016-11-24 16:56 UTC, danrot commented
There is no confirmation dialog when clicking on delete.

2016-11-25 07:33 UTC, danrot commented
The datepicker is still blinking red for a short time after a value is assigned to it for the first time.

2016-11-25 07:41 UTC, wachterjohannes commented
@danrot this problem also exists in the rest of the system. i will take a deeper look into this in an own PR (i think in husky).

2016-11-25 07:45 UTC, wachterjohannes commented
@danrot i have added a todo in the main PR.

2016-11-25 07:48 UTC, merged