Added php-task library
wachterjohannes/sulu pull request #3
Opened 2016-11-22 11:02 UTC by wachterjohannes

Add task entity and controller.

Basic PR: https://github.com/sulu/sulu/pull/3037

2016-11-25 12:54 UTC, chirimoya requested changes

2016-11-25 12:54 UTC, chirimoya commented on composer.json
> +        "php-task/task-bundle": "dev-master",
??? ;-)

2016-11-25 12:54 UTC, chirimoya commented on src/Sulu/Bundle/AutomationBundle/EventListener/TaskEventListener.php
> +class TaskEventListener
explicit call of php-task

2016-11-25 12:54 UTC, chirimoya commented on src/Sulu/Bundle/AutomationBundle/Exception/TaskHandlerNotSupportedException.php
> +        parent::__construct(sprintf("Task-Handler '%s' is not supported.", get_class($taskHandler)));
singel quotes

2016-11-28 06:35 UTC, wachterjohannes commented on composer.json
> +        "php-task/task-bundle": "dev-master",
i will create a new version before we merge this feature into develop

2016-11-28 07:15 UTC, wachterjohannes commented
@chirimoya fixed (:

2016-11-28 08:02 UTC, chirimoya requested changes

2016-11-28 08:02 UTC, chirimoya commented on src/Sulu/Bundle/AutomationBundle/Tasks/Scheduler/TaskSchedulerInterface.php
> +    public function unschedule(TaskInterface $task);
`remove`

2016-11-28 08:02 UTC, chirimoya commented on src/Sulu/Bundle/AutomationBundle/Tasks/Scheduler/TaskSchedulerInterface.php
> +    public function reschedule(TaskInterface $task);
`update`

2016-11-28 08:09 UTC, chirimoya commented
ACK

2016-11-28 08:09 UTC, merged