Feature/enhance ui
wachterjohannes/sulu pull request #8
Opened 2016-11-29 14:12 UTC by wachterjohannes

This PR fixes a few smaller ui issues.

- [ ] Translations (task-name, choose)
- [ ] Delete button in the overlay
- [ ] Only tim should be sortable
- [ ] Icons for running and planned

Main PR: https://github.com/sulu/sulu/pull/3037

2016-11-29 15:04 UTC, danrot commented on src/Sulu/Bundle/AutomationBundle/Resources/public/js/components/automation-tab/main.js
> +                                case 'started':
Wha are the two new states here?

2016-11-29 15:06 UTC, wachterjohannes commented on src/Sulu/Bundle/AutomationBundle/Resources/public/js/components/automation-tab/main.js
> +                                case 'started':
@berndhep wants to have own icons for running and planned tasks.

2016-11-29 15:31 UTC, danrot commented
I always get a 404 for the following URL: `http://sulu-minimal.lo/bundles/suluautomation/js/css/main.css?v=develop`, because there is a `/js`, which doesn't belong there.

2016-11-29 15:35 UTC, danrot requested changes

2016-11-29 15:35 UTC, danrot commented on src/Sulu/Bundle/AutomationBundle/Resources/public/js/components/automation-tab/main.js
> +], function(_, Config, manager, skeletonTemplate, fieldsResponse) {
Should be `config`, shouldn't it?

2016-11-30 06:39 UTC, wachterjohannes commented
@danrot fixed

2016-11-30 07:27 UTC, danrot commented
ACK

2016-11-30 07:30 UTC, merged